INSERT INTO Institutions (Name, Location, Type) VALUES 
('National Museum of Art', 'New York, USA', 'Museum'),
('British Library', 'London, UK', 'Library'),
('University of Florence', 'Florence, Italy', 'University'),
('Smithsonian Institution', 'Washington, USA', 'Museum'),
('Louvre Museum', 'Paris, France', 'Museum'),
('Tokyo National Museum', 'Tokyo, Japan', 'Museum'),
('Berlin State Library', 'Berlin, Germany', 'Library'),
('Harvard University', 'Cambridge, USA', 'University'),
('Oxford University', 'Oxford, UK', 'University'),
('Vatican Library', 'Vatican City', 'Library');

INSERT INTO Collections (Name, Theme) VALUES 
('Ancient Manuscripts', 'Historical Writings'),
('Renaissance Artifacts', 'Art and Culture'),
('Asian Heritage', 'Cultural Heritage'),
('Egyptian Antiquities', 'Ancient Egypt'),
('Medieval Europe', 'Middle Ages'),
('Islamic Art', 'Middle Eastern Art'),
('Pre-Columbian Americas', 'Ancient Civilizations'),
('Modernist Works', '20th Century Art'),
('Greek and Roman Classics', 'Classical Antiquity'),
('Digital Humanities', 'Digitized Collections');

INSERT INTO Artifacts (Name, Description, Period, Origin, InstitutionID, CollectionID) VALUES 
('Roman Coin', 'Ancient Roman currency', '1st Century BC', 'Rome, Italy', 1, 2),
('Chinese Vase', 'Ming Dynasty porcelain', '14th Century', 'China', 6, 3),
('Egyptian Sarcophagus', 'Pharaoh’s burial coffin', '1300 BC', 'Egypt', 5, 4),
('Mayan Stela', 'Carved stone monument', '800 AD', 'Guatemala', 7, 7),
('Greek Amphora', 'Ancient Greek vase', '500 BC', 'Greece', 1, 9),
('Persian Rug', 'Intricate hand-woven textile', '16th Century', 'Iran', 6, 6),
('Medieval Sword', 'Knight’s longsword', '13th Century', 'England', 3, 5),
('Renaissance Painting', 'Oil painting from the Renaissance era', '15th Century', 'Italy', 4, 2),
('Japanese Katana', 'Samurai sword', '17th Century', 'Japan', 6, 3),
('Native American Pottery', 'Handmade clay vessel', '19th Century', 'USA', 8, 7),
('Byzantine Icon', 'Religious painting on wood', '10th Century', 'Byzantium', 2, 5),
('Viking Helmet', 'Iron helmet from the Viking Age', '9th Century', 'Scandinavia', 3, 6),
('Terracotta Warrior', 'Ancient Chinese military statue', '3rd Century BC', 'China', 6, 3),
('Aztec Sun Stone', 'Large carved calendar stone', '15th Century', 'Mexico', 7, 7),
('Babylonian Cylinder Seal', 'Ancient engraved cylinder for stamping', '2000 BC', 'Mesopotamia', 2, 4),
('Inca Gold Mask', 'Gold ceremonial mask', '15th Century', 'Peru', 7, 7),
('Medieval Tapestry', 'Woven fabric depicting historical events', '14th Century', 'France', 4, 5),
('Enamel Reliquary', 'Christian relic container', '12th Century', 'Germany', 3, 5),
('Assyrian Relief', 'Carved stone panel depicting a battle', '7th Century BC', 'Iraq', 2, 4),
('Nigerian Bronze Head', 'Cast bronze head from the Benin Kingdom', '16th Century', 'Nigeria', 8, 3),
('Gothic Chalice', 'Ornate medieval cup for religious use', '13th Century', 'Italy', 4, 5),
('Olmec Colossal Head', 'Giant carved stone head', '900 BC', 'Mexico', 7, 7),
('Phoenician Glass Bottle', 'Ancient glass bottle', '6th Century BC', 'Lebanon', 2, 4),
('Mughal Miniature Painting', 'Intricate small-scale painting', '17th Century', 'India', 6, 3),
('Etruscan Helmet', 'Bronze helmet from Etruscan civilization', '5th Century BC', 'Italy', 1, 9),
('Russian Orthodox Icon', 'Religious painting with gold leaf', '16th Century', 'Russia', 8, 6),
('Indus Valley Seals', 'Carved stone seals with script', '2500 BC', 'India/Pakistan', 6, 3),
('Medieval Manuscript', 'Illuminated manuscript page', '14th Century', 'France', 4, 5),
('Tibetan Thangka', 'Buddhist silk painting', '18th Century', 'Tibet', 6, 3),
('Celtic Torc', 'Gold neck ring from Iron Age', '4th Century BC', 'Ireland', 3, 9),
('Bactrian Gold Crown', 'Ancient nomadic gold crown', '1st Century BC', 'Afghanistan', 2, 4),
('Mosaic from Pompeii', 'Roman floor mosaic', '1st Century AD', 'Italy', 1, 9),
('Maya Codex', 'Pre-Columbian bark-paper book', '12th Century', 'Mexico', 7, 7),
('Parthenon Fragment', 'Sculptural piece from the Parthenon', '5th Century BC', 'Greece', 1, 9),
('Ancient Egyptian Papyrus', 'Hieroglyphic scroll', '1200 BC', 'Egypt', 5, 4),
('Hawaiian Feather Cloak', 'Royal feather cape', '18th Century', 'Hawaii', 8, 3),
('Sassanian Silver Plate', 'Engraved Persian silver dish', '5th Century', 'Iran', 6, 6),
('Roman Glass Flask', 'Blown glass vessel', '3rd Century AD', 'Rome', 1, 2);

INSERT INTO Historical_Texts (Title, Author, Year, Language, InstitutionID, CollectionID) VALUES 
('Magna Carta', 'Unknown', 1215, 'Latin', 2, 1),
('The Prince', 'Niccolò Machiavelli', 1532, 'Italian', 3, 2),
('Tale of Genji', 'Murasaki Shikibu', 1008, 'Japanese', 6, 3),
('Epic of Gilgamesh', 'Unknown', -2000, 'Akkadian', 7, 4),
('Divine Comedy', 'Dante Alighieri', 1320, 'Italian', 3, 2),
('Quran', 'Multiple Authors', 632, 'Arabic', 6, 6),
('Beowulf', 'Unknown', 975, 'Old English', 7, 5),
('Canterbury Tales', 'Geoffrey Chaucer', 1400, 'Middle English', 3, 5),
('Art of War', 'Sun Tzu', -500, 'Chinese', 6, 3),
('Federalist Papers', 'Alexander Hamilton et al.', 1788, 'English', 8, 9);

INSERT INTO Exhibitions (Title, StartDate, EndDate, InstitutionID) VALUES 
('Ancient Rome Rediscovered', '2024-03-01', '2024-06-30', 1),
('Florentine Renaissance', '2024-04-15', '2024-07-15', 3),
('Egyptian Mysteries', '2024-05-10', '2024-08-20', 5),
('Asian Artifacts', '2024-06-01', '2024-09-01', 6),
('Islamic Golden Age', '2024-07-01', '2024-10-15', 6),
('Medieval Chronicles', '2024-08-01', '2024-11-30', 7),
('Pre-Columbian Discoveries', '2024-09-01', '2024-12-15', 7),
('Modernist Visions', '2024-10-01', '2025-01-31', 8),
('Greek and Roman Classics', '2024-11-01', '2025-02-28', 1),
('Digital Humanities Showcase', '2024-12-01', '2025-03-31', 9),
('Japanese Edo Art', '2025-01-01', '2025-04-30', 6),
('Islamic Calligraphy', '2025-02-01', '2025-05-31', 6),
('American Indigenous Heritage', '2025-03-01', '2025-06-30', 8),
('Renaissance Sculpture', '2025-04-01', '2025-07-31', 3),
('Enlightenment Literature', '2025-05-01', '2025-08-31', 2);

INSERT INTO Public_Engagements (ExhibitionID, VisitorCount, Feedback) VALUES 
(1, 5000, 'Amazing collection of Roman artifacts!'),
(2, 7000, 'Loved the paintings and sculptures.'),
(3, 6500, 'The Egyptian relics were fascinating!'),
(4, 7200, 'Beautiful Asian art collection.'),
(5, 6100, 'Impressive Islamic artwork and calligraphy.'),
(6, 5900, 'Medieval history was well presented.'),
(7, 6700, 'Interesting look at Pre-Columbian societies.'),
(8, 7500, 'Modernist pieces were thought-provoking.'),
(9, 8100, 'Great insights into classical Greek and Roman works.'),
(10, 8300, 'Wonderful exhibition on digital humanities!'),
(11, 6200, 'Japanese Edo art was stunning.'),
(12, 5800, 'Fantastic calligraphy from the Islamic world.'),
(13, 7300, 'Indigenous American heritage was well represented.'),
(14, 7700, 'Renaissance sculptures were awe-inspiring.'),
(15, 6400, 'Enlightenment literature was fascinating.'),
(1, 5100, 'Loved the interactive elements in Ancient Rome Rediscovered.'),
(2, 6900, 'The artistic elements of the Florentine Renaissance were breathtaking.'),
(3, 6700, 'The preservation of Egyptian artifacts was commendable.'),
(4, 7400, 'Great storytelling through Asian artifacts.'),
(5, 6800, 'Enjoyed the historical insights into the Islamic Golden Age.');

INSERT INTO Researchers (Name, Affiliation, Email) VALUES 
('Dr. Anna Lee', 'Harvard University', 'alee@harvard.edu'),
('Prof. Michael Tan', 'Oxford University', 'mtan@ox.ac.uk'),
('Dr. Susan Carter', 'Stanford University', 'scarter@stanford.edu'),
('Dr. James Wong', 'MIT', 'jwong@mit.edu'),
('Prof. Linda Scott', 'Cambridge University', 'lscott@cam.ac.uk'),
('Dr. Henry Adams', 'Yale University', 'hadams@yale.edu'),
('Dr. Olivia Chen', 'Princeton University', 'ochen@princeton.edu'),
('Dr. Robert Smith', 'Columbia University', 'rsmith@columbia.edu'),
('Dr. Emily Zhang', 'University of Chicago', 'ezhang@uchicago.edu'),
('Dr. William Turner', 'University of Toronto', 'wturner@utoronto.ca'),
('Dr. Natalie Brown', 'University of Melbourne', 'nbrown@unimelb.edu.au'),
('Dr. Daniel Clark', 'University of Edinburgh', 'dclark@ed.ac.uk'),
('Dr. Sophia Patel', 'University of California, Berkeley', 'spatel@berkeley.edu'),
('Dr. George White', 'University of Michigan', 'gwhite@umich.edu'),
('Prof. Karen Hall', 'University of Sydney', 'khall@sydney.edu.au'),
('Dr. Thomas Evans', 'University of Oxford', 'tevans@ox.ac.uk'),
('Dr. Rachel Green', 'Harvard University', 'rgreen@harvard.edu'),
('Dr. Anthony Lewis', 'Stanford University', 'alewis@stanford.edu'),
('Prof. Lisa Robinson', 'MIT', 'lrobinson@mit.edu'),
('Dr. Benjamin King', 'Cambridge University', 'bking@cam.ac.uk'),
('Dr. Sarah Moore', 'Yale University', 'smoore@yale.edu'),
('Dr. Christopher Adams', 'Princeton University', 'cadams@princeton.edu'),
('Dr. Megan Lee', 'Columbia University', 'mlee@columbia.edu'),
('Dr. Jonathan Black', 'University of Chicago', 'jblack@uchicago.edu'),
('Dr. Laura Wilson', 'University of Toronto', 'lwilson@utoronto.ca'),
('Dr. Patrick Johnson', 'University of Melbourne', 'pjohnson@unimelb.edu.au'),
('Dr. Samantha Carter', 'University of Edinburgh', 'scarter@ed.ac.uk'),
('Dr. Matthew Wright', 'University of California, Berkeley', 'mwright@berkeley.edu'),
('Dr. Victoria Collins', 'University of Michigan', 'vcollins@umich.edu'),
('Dr. Charles Harris', 'University of Sydney', 'charris@sydney.edu.au'),
('Dr. Elizabeth Nelson', 'University of Oxford', 'enelson@ox.ac.uk'),
('Dr. Kevin Rogers', 'Harvard University', 'krogers@harvard.edu'),
('Dr. Angela Scott', 'Stanford University', 'ascott@stanford.edu'),
('Dr. Richard Clark', 'MIT', 'rclark@mit.edu'),
('Dr. Michelle Baker', 'Cambridge University', 'mbaker@cam.ac.uk'),
('Dr. Steven Harris', 'Yale University', 'sharris@yale.edu'),
('Dr. Caroline Evans', 'Princeton University', 'cevans@princeton.edu'),
('Dr. Brian Foster', 'Columbia University', 'bfoster@columbia.edu'),
('Dr. Amanda Young', 'University of Chicago', 'ayoung@uchicago.edu'),
('Dr. Nicholas Hall', 'University of Toronto', 'nhall@utoronto.ca'),
('Dr. Julia Adams', 'University of Melbourne', 'jadams@unimelb.edu.au'),
('Dr. Eric Mitchell', 'University of Edinburgh', 'emitchell@ed.ac.uk'),
('Dr. Rebecca Thomas', 'University of California, Berkeley', 'rthomas@berkeley.edu'),
('Dr. Sean Williams', 'University of Michigan', 'swilliams@umich.edu'),
('Dr. Ashley Cooper', 'University of Sydney', 'acooper@sydney.edu.au'),
('Dr. Andrew Campbell', 'University of Oxford', 'acampbell@ox.ac.uk'),
('Dr. Lauren Martinez', 'Harvard University', 'lmartinez@harvard.edu'),
('Dr. Paul Anderson', 'Stanford University', 'panderson@stanford.edu');

INSERT INTO Researcher_Texts (ResearcherID, TextID) VALUES
(1, 2), (2, 4), (3, 6), (4, 8), (5, 10),
(6, 12), (7, 14), (8, 16), (9, 18), (10, 20),
(11, 1), (12, 3), (13, 5), (14, 7), (15, 9),
(16, 11), (17, 13), (18, 15), (19, 17), (20, 19);

INSERT INTO Exhibition_Artifacts (ExhibitionID, ArtifactID) VALUES
(1, 2), (2, 4), (3, 6), (4, 8), (5, 10),
(6, 12), (7, 14), (8, 16), (9, 18), (10, 20),
(11, 1), (12, 3), (13, 5), (14, 7), (15, 9),
(16, 11), (17, 13), (18, 15), (19, 17), (20, 19);

INSERT INTO Researcher_Exhibitions (ResearcherID, ExhibitionID) VALUES
(1, 3), (2, 5), (3, 7), (4, 2), (5, 8),
(6, 10), (7, 12), (8, 1), (9, 4), (10, 6),
(11, 14), (12, 16), (13, 18), (14, 20), (15, 9),
(16, 11), (17, 13), (18, 15), (19, 17), (20, 19);

